### PR TITLE
Added +tabs mixin implemented with jQuery

### PR DESCRIPTION
**Pull request by Riernar**
Here is amixin implementation of a tab selection, that use Roll20's jQuery implementation to change display.

## New Features
+ `+tabs(name="tabs")` mixin that makes it possible to add a tab selection using jQuery
    + a nested `+tab(name)` mixin, only available within `+tabs`, to add a tab to the tab selection
+ New k-scaffold data, exports and handlers to register the required jQuery callbacks
+ New `k.scss` user-facing file, that should be `@use`-ed in the user's sheet, to add the (minimal) SCSS needed for the above mixin to work out of the box. Only the bare minimum styling (hidden/visible) is provided.

The code are in dedicated files, because the `_htmlelements.pug` is getting big (>1000lines). I'll inline the code if you prefer, no problem.

### CODE REVIEW

**Comment by Riernar** [comment]
I haven't really used pugdoc before, so I'm not sure the nested documentation will be detected.

**Comment by Kurohyou** [comment]
Took me a bit to get some time to look at this. This looks pretty good overall.

Some general notes and things I think we should discuss:

### SCSS

I've been meaning to write an SCSS module for use with the K-scaffold. This looks like a great start to that

### Tabs mixin/js

This is a thing of beauty! I had no idea that we could get essentially named blocks like this. I may have to look at redesigning some of the other mixins to take advantage of this. There are a few pieces that I'd like to see changed.

1. The tab button container (`tab-header`) should be a nav element instead of a standard div. 
    - This helps to make the sheet more accessible as screen readers will actually recognize the navigation element and properly call it out to the user.
    - Along the same lines, is there anyway that we can provide a way for users to specify what sort of element is used for the tab content? I'd like to allow semantic html elements for this.
2. I think that the tab buttons should be actual action buttons.
    - Similarly to the nav element, this also helps with accessibility as it is using elements according to their semantic meaning, which screen readers frequently use to help parse a site.
    - This would require a slight change to the `tab` mixin call to use a buttonObj instead of just a name. You could look at the `navButton` mixin in `_htmlelements.pug` as an example.
3. The tab listener for these should be a regular Roll20 `on` listener.
    - The `$20` listener cannot be called from chat. This may be an edge case for navigation buttons, but makes more sense to me to leave open the ability to navigate the sheet from chat than to close it off entirely.
    - This allows the tab listeners to tap into the standard K-scaffold listener cascade. Users would even be able to define custom custom functions for their own unique navigation needs.
    - The `$20` listeners frequently don't properly connect when developing a sheet in the sheet sandbox, which can make testing and troubleshooting the sheet difficult
4. I think the class naming schema should follow the modified BEM syntax used in the rest of the scaffold where `--` denotes a modifier of a block and `__` denotes a child of a block. Using this, `tab-header` would become `tab__header` and `tab-header-tabs` would become `tab__header--tabs`.

**Comment by Kurohyou** [comment]
As for the inline code vs. separate files, I've been working on getting away from the god pattern. Modularizing these mixins is on my todo list, it's just behind about 30 other things.

**Comment by Kurohyou** [comment]
Here's some edits I put together to illustrate what I'm thinking of:

### PUG
```js
mixin tabs(name="tabs",activeI = 0)
  - name = actionButtonName(replaceProblems(name));

  - const tabs = [];
  mixin tab(obj={})
    - obj.name = replaceProblems(obj.name ? `${obj.name}` : `tab${tabs.length + 1}`)
    - const tabName = actionButtonName(obj.name);
    - obj.name = `${name} ${obj.name}`;
    - obj.class = `tab-button tab-button-${name}${obj.class ? ` ${obj.class}`:''}`;
    - attributes.class = `${attributes.class}${tabs.length === activeI ? " active-ktab" : ""}`
    - obj.trigger = obj.trigger || {triggeredFuncs:['kNav']};
    - const content = obj.content || '';
    - delete obj.content;
    - tabs.push({name:tabName,obj, attributes, block, content});
  mixin tabButton(obj)
    - obj.name = `nav ${obj.name}`;
    +action(obj)
      block
  - attributes.class = replaceProblems(attributes.class ? attributes.class : "");
  - attributes.class = `tab tab--${name} ${attributes.class}`;
  div&attributes(attributes)

    - block ? block() : undefined;

    nav(class=`tab__header tab__header--${name}`)
      each tab, index in tabs
        +tabButton(tab.obj)
          if tab.content
            != tab.content
    
    div(class=`tab__body tab__body--${name}`)
      each tab, index in tabs
        - tab.attributes.class = replaceProblems(tab.attributes.class ? tab.attributes.class : "");
        - tab.attributes.class = `tab__container tab__container--${name} tab__container--${name}--${tab.name} ${tab.attributes.class}`;
        div(data-tab=tab.name data-container-tab=name)&attributes(tab.attributes)
          - tab.block()
  -
    varObjects["tabDetails"].push({
      name,
      tabs:tabs.map(data => { const {block, ...rest} = data; return rest; } )
    });
```
That still needs some cleaning up; e.g. probably doesn't need the `tabDetails` prop on `varObjects` anymore.
### JS

```js

const kNav = ({trigger,attributes,sections,casc})=>{
    const [container,tab] = (
        trigger.name.match(/nav-(.+?)-(.+)/) ||
        []
    ).slice(1);
    $20(`[data-container-tab="${container}"]`).removeClass('active-ktab');
    $20(`[data-container-tab="${container}"][data-tab="${tab}"]`).addClass('active-ktab');
};
registerFuncs({kNav});
```

### SCSS
```scss
.tab {
  .tab__body {
    .tab__container:not(.active-ktab) {
      display: none !important;
    }
  }
}
```

### Example Usage:
```js
include scaffold/_kpug.pug
+tabs(name="sheet-tabs")(class="outer")
  span before the header
  +tab({content:'tab 1'})(class="tab-vertical")
    span Tab 1 content
  +tab({name:"background",content:'background'})(class="tab_horizontal")
    span Tab background content
+kscript
```

**Comment by Riernar** [comment]
I'll integrate it into the PR, I was just modifying it

**Comment by Riernar** [comment]
I see a lot of the mixins in `_htmlelements.pug` do nothing with the implicit `attributes` argument, not even passing it to the wrapped mixin. Does that means making e.g. a `+action` ignores the attributes passed, so `+action(obj)(data-i18n="")` does the same as  `+action(obj)` ? Or is the implicit argument also implicitly passed along by pug ?

**Comment by Kurohyou** [comment]
I made many of those mixins before I fully understood pug. Updating them to use the attributes syntax is a to-do. You're welcome to update the button chain to do so.

**Comment by Riernar** [comment]
Also is there a reason to use `const <name> = <function expr>` other a function declaration ?

**Comment by Kurohyou** [comment]
The short answer is hoisting and ability to reassign the function..

#### Hoisting

Using the function declaration (or using `var aFunction = function(){}` hoists the function declaration to the top of the scope. This can then cause issues with the code if you try to invoke the function before it's actually been defined. For the K-scaffold's methods there's probably very little difference here, but it's still better practice to not use something that gets hoisted to a place potentially before it's actually defined.

#### Reassignment

Using the function declaration or `var aFunction = function(){}` allows for that variable name to be reassigned to something else later on. Especially for functions, this is almost always a bad idea as you can reassign your `aFunction` to suddenly be a string instead of a function or be a function that works completely differently from the one you're expecting. Using `const` prevents this from happening; you'll still get a crash if you try to do it, but the error message will at least inform you that you erroneously tried to reassign a function.

**Comment by Riernar** [comment]
@Kurohyou 
I integrated all your remarks, I think:

- Everything is using the BEM, with `--` to modify a tag, and `__` to indicate a child
- The `+tabs()` mixin accepts a second argument for the index of the tab active by defaul
- the `+tab()` mixin:
  + takes its `tabName` as a standalone parameter (quicker to type for simple tabs)
  + takes a second `button` parameter used to build the buttons
  + takes a third argument `container` that is the name of the tag that encompasses the whole tab. div by default, but can be changed.
  - there is a check that tabs name are not duplicated, because they would otherwise conflict (the display mecanism is based on actual names)
  - Switched to using action button and k-scaffold trigger mecanism. Provided a default trigger, with a default `triggeredFunc` that switch tabs. Everything works by default, the user can override the behavior.
  - Used a `<nav>` element instead of a div for the header
  - also the button mixin now pass the implicit `attributes` down

**Comment by Kurohyou** [comment]
Dang, you have been busy! Reviewing now.

**Review by Kurohyou — APPROVED** [review]
Looks good to me. Thanks for integrating those requests.

**Pull request merged**
